modLoader="javafml"
loaderVersion="${loader_version_range_neoforge}"
issueTrackerURL="${issues_url}"

license="${license_name}"
[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage_url}"
logoFile="assets/${mod_id}/icon.png"
authors="${mod_author}"
description='''
${description}
'''
displayTest="IGNORE_ALL_VERSION"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range_forge}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="neoforge"
    mandatory=true
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"
