# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.
name: build
on: [pull_request, push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      # to cache gradle files
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true
          dependency-graph: generate-and-submit
# Already needs to be executable, so the dirty check is correct
#      - name: make gradle wrapper executable
#        if: ${{ runner.os != 'Windows' }}
#        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build
      - name: capture build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: 'versions/**/build/libs/*.jar'
#      - name: Test Report
#        uses: dorny/test-reporter@v1
#        if: success() || failure()
#        with:
#          name: JUnit Tests
#          path: '**/build/test-results/test/TEST-*.xml'
#          reporter: java-junit        