name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: make gradle wrapper executable
        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build -Pbuild.release=true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'versions/**/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-1.19.3-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.19.3 - Forge
          version-type: beta
          files: 'versions/1.19.3-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.3
      - name: Publish-1.19.3-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.19.3 - Forge
          files: 'versions/1.19.3-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.3
      - name: Publish-1.19.3-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.19.3 - Fabric
          files: 'versions/1.19.3-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.3
      - name: Publish-1.19.3-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.19.3 - Fabric
          files: 'versions/1.19.3-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.3
      - name: Publish-1.19.4-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.19.4 - Forge
          version-type: beta
          files: 'versions/1.19.4-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.4
      - name: Publish-1.19.4-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.19.4 - Forge
          files: 'versions/1.19.4-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.4
      - name: Publish-1.19.4-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.19.4 - Fabric
          files: 'versions/1.19.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.4
      - name: Publish-1.19.4-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.19.4 - Fabric
          files: 'versions/1.19.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.19.4
      - name: Publish-1.20.1-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.1 - Forge
          version-type: beta
          files: 'versions/1.20.1-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.1
      - name: Publish-1.20.1-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.1 - Forge
          files: 'versions/1.20.1-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.1
      - name: Publish-1.20.1-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.1 - Fabric
          files: 'versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.1
      - name: Publish-1.20.1-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.1 - Fabric
          files: 'versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.1
      - name: Publish-1.20.2-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.2 - Forge
          version-type: beta
          files: 'versions/1.20.2-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.2 - Forge
          files: 'versions/1.20.2-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-neoforge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.2 - NeoForge
          version-type: beta
          files: 'versions/1.20.2-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-neoforge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.2 - NeoForge
          files: 'versions/1.20.2-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.2 - Fabric
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.2-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.2 - Fabric
          files: 'versions/1.20.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.2
      - name: Publish-1.20.4-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.4 - Forge
          version-type: beta
          files: 'versions/1.20.4-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.4-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.4 - Forge
          files: 'versions/1.20.4-forge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.4-neoforge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.4 - NeoForge
          version-type: beta
          files: 'versions/1.20.4-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.4-neoforge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.4 - NeoForge
          files: 'versions/1.20.4-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.4-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.4 - Fabric
          files: 'versions/1.20.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.4-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.4 - Fabric
          files: 'versions/1.20.4-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.4
      - name: Publish-1.20.6-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.6 - Forge
          version-type: beta
          files: 'versions/1.20.6-forge/build/libs/!(*-@(dev|sources|javadoc)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.6 - Forge
          files: 'versions/1.20.6-forge/build/libs/!(*-@(dev|sources|javadoc)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-neoforge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.6 - NeoForge
          version-type: beta
          files: 'versions/1.20.6-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-neoforge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.6 - NeoForge
          files: 'versions/1.20.6-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.6 - Fabric
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.6 - Fabric
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.21-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.21(.1) - Forge
          version-type: beta
          files: 'versions/1.21-forge/build/libs/!(*-@(dev|sources|javadoc)).jar'
          game-versions: 1.21.x
      - name: Publish-1.21-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.21(.1) - Forge
          files: 'versions/1.21-forge/build/libs/!(*-@(dev|sources|javadoc)).jar'
          game-versions: 1.21.x
      - name: Publish-1.21-neoforge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.21(.1) - NeoForge
          version-type: beta
          files: 'versions/1.21-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.x
      - name: Publish-1.21-neoforge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.21(.1) - NeoForge
          files: 'versions/1.21-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.x
      - name: Publish-1.21-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.21(.1) - Fabric
          files: 'versions/1.21-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.x
      - name: Publish-1.21-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.21(.1) - Fabric
          files: 'versions/1.21-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.x
      - name: Publish-1.21.2-neoforge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.21.2 - NeoForge
          version-type: beta
          files: 'versions/1.21.2-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.2
      - name: Publish-1.21.2-neoforge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.21.2 - NeoForge
          files: 'versions/1.21.2-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.2
      - name: Publish-1.21.2-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.21.2 - Fabric
          files: 'versions/1.21.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.2
      - name: Publish-1.21.2-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.21.2 - Fabric
          files: 'versions/1.21.2-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.21.2
