name: Create Release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: setup jdk 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: make gradle wrapper executable
        run: chmod +x ./gradlecw
      - name: build
        run: ./gradlecw build -Pbuild.release=true
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: 'versions/**/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
      - name: Publish-1.20.6-forge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.6 - Forge
          version-type: beta
          files: 'versions/1.20.6-forge/build/libs/!(*-@(dev|sources|javadoc)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-forge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: forge
          name: ${{github.ref_name}}-1.20.6 - Forge
          files: 'versions/1.20.6-forge/build/libs/!(*-@(dev|sources|javadoc)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-neoforge-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.6 - NeoForge
          version-type: beta
          files: 'versions/1.20.6-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-neoforge-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: neoforge
          name: ${{github.ref_name}}-1.20.6 - NeoForge
          files: 'versions/1.20.6-neoforge/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-fabric-Curseforge
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          curseforge-id: 448233
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.6 - Fabric
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
      - name: Publish-1.20.6-fabric-Modrinth
        uses: Kir-Antipov/mc-publish@v3.3.0
        with:
          modrinth-id: NNAgCjsB
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          loaders: fabric
          name: ${{github.ref_name}}-1.20.6 - Fabric
          files: 'versions/1.20.6-fabric/build/libs/!(*-@(dev|sources|javadoc|all)).jar'
          game-versions: 1.20.6
